services:
  app:
    image: file_sharing_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:postgresql://files_db:5432/postgres
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: pass
    depends_on:
      - files_db

  files_db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
